### ISSUE TITLE
Программу не возможно запустить повторно после вылета.

### ISSUE THREAD

**Issue by KASaLEX-2020** [gmh4589/fungi#1]
Столкнулся с такой проблемой, если скормить программе не известный формат с текстурой внутри она просто-напросто вылетает... но проблема в том, что после этого программа больше не запускается! Проверил на двух компьютерах с Виндовс 11, программа вылетела и больше запустить её на машине не возможно даже после перезагрузки системы.
P.S. собрал программу из исходников, но всё равно её больше нельзя запустить на целевой машине!

**Comment by gmh4589** [comment]
Исправлено. Перед запуском программы теперь удаляются временные файлы
